---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
Try dendogram trial 

```{r}
rm(list=ls())
library(dendextend)
path="~/illumina/TEST_dendo/"
setwd(path)
data<-readRDS("test.rds")

dd<-dist(data,method = "euclidean")
hc<-hclust(dd,method="average")
dend<-as.dendrogram(hc)
dend<-color_branches(dend,h=8)

dend %>% set("leaves_pch",2) %>% set("nodes_cex",0.7) %>% set("labels_cex",0.1) %>% plot(axes=T,cex=0.5,type="rectangle")

```

I have some question:

1) How can improve the  quality of the image?
2) with 617  rows it is possible to plot quality dendrogram with clear labels?
3)how can see only one of the  cluster...I mean to plot only the  purple cluster
```{r}
dend %>% 
   raise.dendrogram (-10) %>%  set("labels_cex",0.2)%>%
   plot(main = "One point lower", ylim = c(0,3))
```
```{r}
dend %>% set("leaves_pch", 19) %>% set("leaves_cex", 2) %>% set("leaves_col", 2) %>% # adjust the leaves
   hang.dendrogram(hang_height = 1) %>%  set("labels_cex",0.1)%>%
   plot(main = "Hanging a tree (but lower)",horiz=T)
```

